Test: Add test to verify requests are not scheduled if limit is exceeded
ceph/dmclock pull request #83
Opened 2020-09-24 17:52 UTC by sseshasa

Add a test to verify that when a client exceeds its limit, the
scheduler does not schedule the requests from that client but instead
responds with a future request type until the limit is restored.

The motivation for adding this test is that this scenario is currently not
handled within the mClockScheduler::dequeue() function i.e. handle
future request type response. The code to handle this case is currently
being put in place and tested as part of another PR.

2020-09-24 18:16 UTC, athanatos approved these changes

2020-09-24 20:04 UTC, ivancich requested changes
Looks good overall. Please use ceph coding style as documented at https://github.com/ceph/ceph/blob/master/CodingStyle . Otherwise, I approve.

2020-09-24 20:04 UTC, ivancich commented on test/test_dmclock_server.cc
> +        if (client1 == c) return &info1;
Please use ceph coding style as documented at https://github.com/ceph/ceph/blob/master/CodingStyle .

2020-09-24 20:04 UTC, ivancich commented on test/test_dmclock_server.cc
> +        } else ADD_FAILURE() << "got request from neither of two clients";
Please use ceph coding style as documented at https://github.com/ceph/ceph/blob/master/CodingStyle .

2020-09-24 20:04 UTC, ivancich commented on test/test_dmclock_server.cc
> +        } else ADD_FAILURE() << "got request from neither of two clients";
Please use ceph coding style as documented at https://github.com/ceph/ceph/blob/master/CodingStyle .

2020-09-24 20:04 UTC, ivancich commented on test/test_dmclock_server.cc
> +      for (int i = 0; i< 2; ++i) {
missing space

2020-09-25 04:56 UTC, sseshasa commented on test/test_dmclock_server.cc
> +        if (client1 == c) return &info1;
Done.

2020-09-25 04:57 UTC, sseshasa commented on test/test_dmclock_server.cc
> +        } else ADD_FAILURE() << "got request from neither of two clients";
Done.

2020-09-25 04:57 UTC, sseshasa commented on test/test_dmclock_server.cc
> +        } else ADD_FAILURE() << "got request from neither of two clients";
Done.

2020-09-25 04:57 UTC, sseshasa commented on test/test_dmclock_server.cc
> +      for (int i = 0; i< 2; ++i) {
Fixed.

2020-09-25 04:59 UTC, sseshasa commented
> Looks good overall. Please use ceph coding style as documented at https://github.com/ceph/ceph/blob/master/CodingStyle . Otherwise, I approve.

Thanks! There are other tests in the file where similar coding style needs to be adopted. That could be taken up as part of another PR.

2020-09-25 14:43 UTC, ivancich commented
> > Looks good overall. Please use ceph coding style as documented at https://github.com/ceph/ceph/blob/master/CodingStyle . Otherwise, I approve.
> 
> Thanks! There are other tests in the file where similar coding style needs to be adopted. That could be taken up as part of another PR.

Agreed, a clean-up PR is in order. And I'm probably responsible for some of the code that needs the clean-up.

2020-09-25 14:44 UTC, ivancich approved these changes

2020-09-25 14:45 UTC, merged